/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attachment {
  'contentType' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'uploadTime' : bigint,
}
export interface BookingRequest {
  'id' : bigint,
  'destination_address' : string,
  'status' : BookingStatus,
  'pickup_address' : string,
  'paymentMethod' : string,
  'pickup_postal_code' : string,
  'submit_time' : bigint,
  'cab_rating' : [] | [bigint],
  'cancel_reason' : [] | [string],
  'email' : string,
  'pickup_time' : bigint,
  'first_name' : string,
  'last_name' : string,
  'comments' : string,
  'phone_number' : string,
  'destination_postal_code' : string,
  'driver_rating' : [] | [bigint],
  'submitted_by' : Principal,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'refused' : null };
export interface CustomerProfile {
  'name' : string,
  'preferredPaymentMethod' : [] | [PaymentMethod],
}
export interface DriverProfile {
  'cabNumber' : string,
  'vehicleType' : VehicleType,
  'fullName' : string,
  'yearOfManufacture' : bigint,
}
export type ExternalBlob = Uint8Array;
export type PaymentMethod = { 'UPI' : null } |
  { 'creditCard' : null } |
  { 'cash' : null } |
  { 'debitCard' : null };
export interface RateCard {
  'suv' : bigint,
  'mini' : bigint,
  'sedan' : bigint,
  'premiumSuv' : bigint,
}
export interface ReferralBonus {
  'driverBonus' : bigint,
  'customerBonus' : bigint,
}
export type UserProfile = { 'customer' : CustomerProfile } |
  { 'driver' : DriverProfile };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VehicleType = { 'suv' : null } |
  { 'mini' : null } |
  { 'sedan' : null } |
  { 'premiumSuv' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyReferralCode' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardReferralBonuses' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'generateReferralCode' : ActorMethod<[], string>,
  'getAllBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getAttachment' : ActorMethod<
    [{ 'cab' : null } | { 'driver' : null }, Principal],
    [] | [Attachment]
  >,
  'getBooking' : ActorMethod<[bigint], BookingRequest>,
  'getCallerAttachment' : ActorMethod<
    [{ 'cab' : null } | { 'driver' : null }],
    [] | [Attachment]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRateCard' : ActorMethod<[], RateCard>,
  'getReferralBonus' : ActorMethod<[], [] | [ReferralBonus]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBooking' : ActorMethod<[BookingRequest], bigint>,
  'updateRateCard' : ActorMethod<[RateCard], undefined>,
  'uploadAttachment' : ActorMethod<
    [{ 'cab' : null } | { 'driver' : null }, ExternalBlob, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];