/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'refused' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'destination_address' : IDL.Text,
  'status' : BookingStatus,
  'pickup_address' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'pickup_postal_code' : IDL.Text,
  'submit_time' : IDL.Int,
  'cab_rating' : IDL.Opt(IDL.Nat),
  'cancel_reason' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'driver_location' : IDL.Opt(Location),
  'pickup_time' : IDL.Nat,
  'assigned_driver' : IDL.Opt(IDL.Principal),
  'first_name' : IDL.Text,
  'last_name' : IDL.Text,
  'comments' : IDL.Text,
  'phone_number' : IDL.Text,
  'destination_postal_code' : IDL.Text,
  'driver_rating' : IDL.Opt(IDL.Nat),
  'submitted_by' : IDL.Principal,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Attachment = IDL.Record({
  'contentType' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'uploadTime' : IDL.Int,
});
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'creditCard' : IDL.Null,
  'cash' : IDL.Null,
  'debitCard' : IDL.Null,
});
export const CustomerProfile = IDL.Record({
  'name' : IDL.Text,
  'preferredPaymentMethod' : IDL.Opt(PaymentMethod),
});
export const VehicleType = IDL.Variant({
  'suv' : IDL.Null,
  'mini' : IDL.Null,
  'sedan' : IDL.Null,
  'premiumSuv' : IDL.Null,
});
export const DriverProfile = IDL.Record({
  'cabNumber' : IDL.Text,
  'vehicleType' : VehicleType,
  'fullName' : IDL.Text,
  'yearOfManufacture' : IDL.Nat,
});
export const UserProfile = IDL.Variant({
  'customer' : CustomerProfile,
  'driver' : DriverProfile,
});
export const RateCard = IDL.Record({
  'suv' : IDL.Nat,
  'mini' : IDL.Nat,
  'sedan' : IDL.Nat,
  'premiumSuv' : IDL.Nat,
});
export const ReferralBonus = IDL.Record({
  'driverBonus' : IDL.Nat,
  'customerBonus' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyReferralCode' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDriver' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'awardReferralBonuses' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'generateReferralCode' : IDL.Func([], [IDL.Text], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getAttachment' : IDL.Func(
      [IDL.Variant({ 'cab' : IDL.Null, 'driver' : IDL.Null }), IDL.Principal],
      [IDL.Opt(Attachment)],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Nat], [BookingRequest], ['query']),
  'getCallerAttachment' : IDL.Func(
      [IDL.Variant({ 'cab' : IDL.Null, 'driver' : IDL.Null })],
      [IDL.Opt(Attachment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriverLocation' : IDL.Func([IDL.Nat], [IDL.Opt(Location)], ['query']),
  'getRateCard' : IDL.Func([], [RateCard], ['query']),
  'getReferralBonus' : IDL.Func([], [IDL.Opt(ReferralBonus)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBooking' : IDL.Func([BookingRequest], [IDL.Nat], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateDriverLocation' : IDL.Func([IDL.Nat, Location], [], []),
  'updateRateCard' : IDL.Func([RateCard], [], []),
  'uploadAttachment' : IDL.Func(
      [
        IDL.Variant({ 'cab' : IDL.Null, 'driver' : IDL.Null }),
        ExternalBlob,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'refused' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'destination_address' : IDL.Text,
    'status' : BookingStatus,
    'pickup_address' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'pickup_postal_code' : IDL.Text,
    'submit_time' : IDL.Int,
    'cab_rating' : IDL.Opt(IDL.Nat),
    'cancel_reason' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'driver_location' : IDL.Opt(Location),
    'pickup_time' : IDL.Nat,
    'assigned_driver' : IDL.Opt(IDL.Principal),
    'first_name' : IDL.Text,
    'last_name' : IDL.Text,
    'comments' : IDL.Text,
    'phone_number' : IDL.Text,
    'destination_postal_code' : IDL.Text,
    'driver_rating' : IDL.Opt(IDL.Nat),
    'submitted_by' : IDL.Principal,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Attachment = IDL.Record({
    'contentType' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'uploadTime' : IDL.Int,
  });
  const PaymentMethod = IDL.Variant({
    'UPI' : IDL.Null,
    'creditCard' : IDL.Null,
    'cash' : IDL.Null,
    'debitCard' : IDL.Null,
  });
  const CustomerProfile = IDL.Record({
    'name' : IDL.Text,
    'preferredPaymentMethod' : IDL.Opt(PaymentMethod),
  });
  const VehicleType = IDL.Variant({
    'suv' : IDL.Null,
    'mini' : IDL.Null,
    'sedan' : IDL.Null,
    'premiumSuv' : IDL.Null,
  });
  const DriverProfile = IDL.Record({
    'cabNumber' : IDL.Text,
    'vehicleType' : VehicleType,
    'fullName' : IDL.Text,
    'yearOfManufacture' : IDL.Nat,
  });
  const UserProfile = IDL.Variant({
    'customer' : CustomerProfile,
    'driver' : DriverProfile,
  });
  const RateCard = IDL.Record({
    'suv' : IDL.Nat,
    'mini' : IDL.Nat,
    'sedan' : IDL.Nat,
    'premiumSuv' : IDL.Nat,
  });
  const ReferralBonus = IDL.Record({
    'driverBonus' : IDL.Nat,
    'customerBonus' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyReferralCode' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDriver' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'awardReferralBonuses' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'generateReferralCode' : IDL.Func([], [IDL.Text], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getAttachment' : IDL.Func(
        [IDL.Variant({ 'cab' : IDL.Null, 'driver' : IDL.Null }), IDL.Principal],
        [IDL.Opt(Attachment)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Nat], [BookingRequest], ['query']),
    'getCallerAttachment' : IDL.Func(
        [IDL.Variant({ 'cab' : IDL.Null, 'driver' : IDL.Null })],
        [IDL.Opt(Attachment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriverLocation' : IDL.Func([IDL.Nat], [IDL.Opt(Location)], ['query']),
    'getRateCard' : IDL.Func([], [RateCard], ['query']),
    'getReferralBonus' : IDL.Func([], [IDL.Opt(ReferralBonus)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBooking' : IDL.Func([BookingRequest], [IDL.Nat], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateDriverLocation' : IDL.Func([IDL.Nat, Location], [], []),
    'updateRateCard' : IDL.Func([RateCard], [], []),
    'uploadAttachment' : IDL.Func(
        [
          IDL.Variant({ 'cab' : IDL.Null, 'driver' : IDL.Null }),
          ExternalBlob,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };