/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CustomerProfile {
    name: string;
    preferredPaymentMethod?: PaymentMethod;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RateCard {
    suv: bigint;
    mini: bigint;
    sedan: bigint;
    premiumSuv: bigint;
}
export interface BookingRequest {
    id: bigint;
    destination_address: string;
    status: BookingStatus;
    pickup_address: string;
    paymentMethod: string;
    pickup_postal_code: string;
    submit_time: bigint;
    cab_rating?: bigint;
    cancel_reason?: string;
    email: string;
    pickup_time: bigint;
    first_name: string;
    last_name: string;
    comments: string;
    phone_number: string;
    destination_postal_code: string;
    driver_rating?: bigint;
    submitted_by: Principal;
}
export interface ReferralBonus {
    driverBonus: bigint;
    customerBonus: bigint;
}
export interface DriverProfile {
    cabNumber: string;
    vehicleType: VehicleType;
    fullName: string;
    yearOfManufacture: bigint;
}
export interface Attachment {
    contentType: string;
    blob: ExternalBlob;
    name: string;
    uploadTime: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserProfile = {
    __kind__: "customer";
    customer: CustomerProfile;
} | {
    __kind__: "driver";
    driver: DriverProfile;
};
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    accepted = "accepted",
    refused = "refused"
}
export enum PaymentMethod {
    UPI = "UPI",
    creditCard = "creditCard",
    cash = "cash",
    debitCard = "debitCard"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cab_driver {
    cab = "cab",
    driver = "driver"
}
export enum VehicleType {
    suv = "suv",
    mini = "mini",
    sedan = "sedan",
    premiumSuv = "premiumSuv"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    applyReferralCode(code: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardReferralBonuses(bookingId: bigint, customerBonus: bigint, driverBonus: bigint): Promise<void>;
    generateReferralCode(): Promise<string>;
    getAllBookings(): Promise<Array<BookingRequest>>;
    getAttachment(attachmentType: Variant_cab_driver, user: Principal): Promise<Attachment | null>;
    getBooking(id: bigint): Promise<BookingRequest>;
    getCallerAttachment(attachmentType: Variant_cab_driver): Promise<Attachment | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getRateCard(): Promise<RateCard>;
    getReferralBonus(): Promise<ReferralBonus | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitBooking(form: BookingRequest): Promise<bigint>;
    updateRateCard(newRateCard: RateCard): Promise<void>;
    uploadAttachment(attachmentType: Variant_cab_driver, file: ExternalBlob, name: string, contentType: string): Promise<void>;
}
import type { Attachment as _Attachment, BookingRequest as _BookingRequest, BookingStatus as _BookingStatus, CustomerProfile as _CustomerProfile, DriverProfile as _DriverProfile, ExternalBlob as _ExternalBlob, PaymentMethod as _PaymentMethod, ReferralBonus as _ReferralBonus, UserProfile as _UserProfile, UserRole as _UserRole, VehicleType as _VehicleType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyReferralCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyReferralCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyReferralCode(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardReferralBonuses(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardReferralBonuses(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardReferralBonuses(arg0, arg1, arg2);
            return result;
        }
    }
    async generateReferralCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReferralCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReferralCode();
            return result;
        }
    }
    async getAllBookings(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttachment(arg0: Variant_cab_driver, arg1: Principal): Promise<Attachment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttachment(to_candid_variant_n16(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttachment(to_candid_variant_n16(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: bigint): Promise<BookingRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_BookingRequest_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_BookingRequest_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAttachment(arg0: Variant_cab_driver): Promise<Attachment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAttachment(to_candid_variant_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAttachment(to_candid_variant_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRateCard(): Promise<RateCard> {
        if (this.processError) {
            try {
                const result = await this.actor.getRateCard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRateCard();
            return result;
        }
    }
    async getReferralBonus(): Promise<ReferralBonus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralBonus();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralBonus();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitBooking(arg0: BookingRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(to_candid_BookingRequest_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(to_candid_BookingRequest_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRateCard(arg0: RateCard): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRateCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRateCard(arg0);
            return result;
        }
    }
    async uploadAttachment(arg0: Variant_cab_driver, arg1: ExternalBlob, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAttachment(to_candid_variant_n16(this._uploadFile, this._downloadFile, arg0), await to_candid_ExternalBlob_n50(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAttachment(to_candid_variant_n16(this._uploadFile, this._downloadFile, arg0), await to_candid_ExternalBlob_n50(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
}
async function from_candid_Attachment_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attachment): Promise<Attachment> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_BookingRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingRequest): BookingRequest {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerProfile): CustomerProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_DriverProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DriverProfile): DriverProfile {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PaymentMethod_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Attachment]): Promise<Attachment | null> {
    return value.length === 0 ? null : await from_candid_Attachment_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentMethod]): PaymentMethod | null {
    return value.length === 0 ? null : from_candid_PaymentMethod_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReferralBonus]): ReferralBonus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    destination_address: string;
    status: _BookingStatus;
    pickup_address: string;
    paymentMethod: string;
    pickup_postal_code: string;
    submit_time: bigint;
    cab_rating: [] | [bigint];
    cancel_reason: [] | [string];
    email: string;
    pickup_time: bigint;
    first_name: string;
    last_name: string;
    comments: string;
    phone_number: string;
    destination_postal_code: string;
    driver_rating: [] | [bigint];
    submitted_by: Principal;
}): {
    id: bigint;
    destination_address: string;
    status: BookingStatus;
    pickup_address: string;
    paymentMethod: string;
    pickup_postal_code: string;
    submit_time: bigint;
    cab_rating?: bigint;
    cancel_reason?: string;
    email: string;
    pickup_time: bigint;
    first_name: string;
    last_name: string;
    comments: string;
    phone_number: string;
    destination_postal_code: string;
    driver_rating?: bigint;
    submitted_by: Principal;
} {
    return {
        id: value.id,
        destination_address: value.destination_address,
        status: from_candid_BookingStatus_n13(_uploadFile, _downloadFile, value.status),
        pickup_address: value.pickup_address,
        paymentMethod: value.paymentMethod,
        pickup_postal_code: value.pickup_postal_code,
        submit_time: value.submit_time,
        cab_rating: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.cab_rating)),
        cancel_reason: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.cancel_reason)),
        email: value.email,
        pickup_time: value.pickup_time,
        first_name: value.first_name,
        last_name: value.last_name,
        comments: value.comments,
        phone_number: value.phone_number,
        destination_postal_code: value.destination_postal_code,
        driver_rating: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.driver_rating)),
        submitted_by: value.submitted_by
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentType: string;
    blob: _ExternalBlob;
    name: string;
    uploadTime: bigint;
}): Promise<{
    contentType: string;
    blob: ExternalBlob;
    name: string;
    uploadTime: bigint;
}> {
    return {
        contentType: value.contentType,
        blob: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        uploadTime: value.uploadTime
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    preferredPaymentMethod: [] | [_PaymentMethod];
}): {
    name: string;
    preferredPaymentMethod?: PaymentMethod;
} {
    return {
        name: value.name,
        preferredPaymentMethod: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.preferredPaymentMethod))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cabNumber: string;
    vehicleType: _VehicleType;
    fullName: string;
    yearOfManufacture: bigint;
}): {
    cabNumber: string;
    vehicleType: VehicleType;
    fullName: string;
    yearOfManufacture: bigint;
} {
    return {
        cabNumber: value.cabNumber,
        vehicleType: from_candid_VehicleType_n31(_uploadFile, _downloadFile, value.vehicleType),
        fullName: value.fullName,
        yearOfManufacture: value.yearOfManufacture
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    refused: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "accepted" in value ? BookingStatus.accepted : "refused" in value ? BookingStatus.refused : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: _CustomerProfile;
} | {
    driver: _DriverProfile;
}): {
    __kind__: "customer";
    customer: CustomerProfile;
} | {
    __kind__: "driver";
    driver: DriverProfile;
} {
    return "customer" in value ? {
        __kind__: "customer",
        customer: from_candid_CustomerProfile_n24(_uploadFile, _downloadFile, value.customer)
    } : "driver" in value ? {
        __kind__: "driver",
        driver: from_candid_DriverProfile_n29(_uploadFile, _downloadFile, value.driver)
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    creditCard: null;
} | {
    cash: null;
} | {
    debitCard: null;
}): PaymentMethod {
    return "UPI" in value ? PaymentMethod.UPI : "creditCard" in value ? PaymentMethod.creditCard : "cash" in value ? PaymentMethod.cash : "debitCard" in value ? PaymentMethod.debitCard : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suv: null;
} | {
    mini: null;
} | {
    sedan: null;
} | {
    premiumSuv: null;
}): VehicleType {
    return "suv" in value ? VehicleType.suv : "mini" in value ? VehicleType.mini : "sedan" in value ? VehicleType.sedan : "premiumSuv" in value ? VehicleType.premiumSuv : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingRequest>): Array<BookingRequest> {
    return value.map((x)=>from_candid_BookingRequest_n11(_uploadFile, _downloadFile, x));
}
function to_candid_BookingRequest_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingRequest): _BookingRequest {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_CustomerProfile_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerProfile): _CustomerProfile {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_DriverProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DriverProfile): _DriverProfile {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PaymentMethod_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cabNumber: string;
    vehicleType: VehicleType;
    fullName: string;
    yearOfManufacture: bigint;
}): {
    cabNumber: string;
    vehicleType: _VehicleType;
    fullName: string;
    yearOfManufacture: bigint;
} {
    return {
        cabNumber: value.cabNumber,
        vehicleType: to_candid_VehicleType_n40(_uploadFile, _downloadFile, value.vehicleType),
        fullName: value.fullName,
        yearOfManufacture: value.yearOfManufacture
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    preferredPaymentMethod?: PaymentMethod;
}): {
    name: string;
    preferredPaymentMethod: [] | [_PaymentMethod];
} {
    return {
        name: value.name,
        preferredPaymentMethod: value.preferredPaymentMethod ? candid_some(to_candid_PaymentMethod_n44(_uploadFile, _downloadFile, value.preferredPaymentMethod)) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    destination_address: string;
    status: BookingStatus;
    pickup_address: string;
    paymentMethod: string;
    pickup_postal_code: string;
    submit_time: bigint;
    cab_rating?: bigint;
    cancel_reason?: string;
    email: string;
    pickup_time: bigint;
    first_name: string;
    last_name: string;
    comments: string;
    phone_number: string;
    destination_postal_code: string;
    driver_rating?: bigint;
    submitted_by: Principal;
}): {
    id: bigint;
    destination_address: string;
    status: _BookingStatus;
    pickup_address: string;
    paymentMethod: string;
    pickup_postal_code: string;
    submit_time: bigint;
    cab_rating: [] | [bigint];
    cancel_reason: [] | [string];
    email: string;
    pickup_time: bigint;
    first_name: string;
    last_name: string;
    comments: string;
    phone_number: string;
    destination_postal_code: string;
    driver_rating: [] | [bigint];
    submitted_by: Principal;
} {
    return {
        id: value.id,
        destination_address: value.destination_address,
        status: to_candid_BookingStatus_n48(_uploadFile, _downloadFile, value.status),
        pickup_address: value.pickup_address,
        paymentMethod: value.paymentMethod,
        pickup_postal_code: value.pickup_postal_code,
        submit_time: value.submit_time,
        cab_rating: value.cab_rating ? candid_some(value.cab_rating) : candid_none(),
        cancel_reason: value.cancel_reason ? candid_some(value.cancel_reason) : candid_none(),
        email: value.email,
        pickup_time: value.pickup_time,
        first_name: value.first_name,
        last_name: value.last_name,
        comments: value.comments,
        phone_number: value.phone_number,
        destination_postal_code: value.destination_postal_code,
        driver_rating: value.driver_rating ? candid_some(value.driver_rating) : candid_none(),
        submitted_by: value.submitted_by
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cab_driver): {
    cab: null;
} | {
    driver: null;
} {
    return value == Variant_cab_driver.cab ? {
        cab: null
    } : value == Variant_cab_driver.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "customer";
    customer: CustomerProfile;
} | {
    __kind__: "driver";
    driver: DriverProfile;
}): {
    customer: _CustomerProfile;
} | {
    driver: _DriverProfile;
} {
    return value.__kind__ === "customer" ? {
        customer: to_candid_CustomerProfile_n42(_uploadFile, _downloadFile, value.customer)
    } : value.__kind__ === "driver" ? {
        driver: to_candid_DriverProfile_n38(_uploadFile, _downloadFile, value.driver)
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    suv: null;
} | {
    mini: null;
} | {
    sedan: null;
} | {
    premiumSuv: null;
} {
    return value == VehicleType.suv ? {
        suv: null
    } : value == VehicleType.mini ? {
        mini: null
    } : value == VehicleType.sedan ? {
        sedan: null
    } : value == VehicleType.premiumSuv ? {
        premiumSuv: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    UPI: null;
} | {
    creditCard: null;
} | {
    cash: null;
} | {
    debitCard: null;
} {
    return value == PaymentMethod.UPI ? {
        UPI: null
    } : value == PaymentMethod.creditCard ? {
        creditCard: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.debitCard ? {
        debitCard: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    refused: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.accepted ? {
        accepted: null
    } : value == BookingStatus.refused ? {
        refused: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
